const backendApiV1 = "http://localhost:5000/api/v1";
export const backendUrl = {
  admin: {
    signup: `${backendApiV1}/admin/signup`,
    login: `${backendApiV1}/admin/login`,
    logout: `${backendApiV1}/admin/logout`,
    verifyAccount: `${backendApiV1}/admin/verify-account`,
    verifyToken: `${backendApiV1}/admin/verify/:token`,
    forgetPassword: `${backendApiV1}/admin/forget-password`,
    resetPassword: `${backendApiV1}/admin/reset-password/:token`,
    me: `${backendApiV1}/admin/me`,
    updateMe: `${backendApiV1}/admin/me`,
    changePassword: `${backendApiV1}/admin/me/change-password`,
    createCompany: `${backendApiV1}/admin/companies`,
    getCompanies: `${backendApiV1}/admin/companies`,
    getCompanyById: `${backendApiV1}/admin/companies/:companyId`,
    updateCompany: `${backendApiV1}/admin/companies/:companyId`,
    deleteCompany: `${backendApiV1}/admin/companies/:companyId`,
    changeCompanyPlan: `${backendApiV1}/admin/companies/:companyId/change-plan`,
    changeCompanyStatus: `${backendApiV1}/admin/companies/:companyId/change-status`,
    getCompanyEmployees: `${backendApiV1}/admin/companies/:companyId/employees`,
    createCompanyEmployee: `${backendApiV1}/admin/companies/:companyId/employees`,
    getCompanyEmployeeById: `${backendApiV1}/admin/companies/:companyId/employees/:employeeId`,
    getEmployees: `${backendApiV1}/admin/employees`,
    getEmployeeById: `${backendApiV1}/admin/employees/:employeeId`,
    updateEmployee: `${backendApiV1}/admin/employees/:employeeId`,
    deleteEmployee: `${backendApiV1}/admin/employees/:employeeId`,
    changeEmployeeStatus: `${backendApiV1}/admin/employees/:employeeId/change-status`,
    getIndividuals: `${backendApiV1}/admin/individuals`,
    getIndividualById: `${backendApiV1}/admin/individuals/:individualId`,
    updateIndividual: `${backendApiV1}/admin/individuals/:individualId`,
    deleteIndividual: `${backendApiV1}/admin/individuals/:individualId`,
    changeIndividualStatus: `${backendApiV1}/admin/individuals/:individualId/change-status`,
  },
  company: {},
  employee: {},
  individual: {},
};
