export const departments = [
  { value: "Administrative", label: "Administrative" },
  { value: "HR", label: "HR" },
  { value: "Operations_Delivery", label: "Operations Delivery" },
  {
    value: "Product_Service_Development",
    label: "Product Service Development",
  },
  { value: "Purchasing", label: "Purchasing" },
  { value: "Sales", label: "Sales" },
  { value: "Marketing", label: "Marketing" },
  { value: "Accounting", label: "Accounting" },
  { value: "Finance", label: "Finance" },
  { value: "IT", label: "IT" },
  { value: "Legal", label: "Legal" },
  { value: "Research_and_Development", label: "Research and Development" },
  { value: "Customer_Service", label: "Customer Service" },
  { value: "Training", label: "Training" },
  { value: "Quality_Assurance", label: "Quality Assurance" },
  { value: "Manufacturing", label: "Manufacturing" },
  { value: "Engineering", label: "Engineering" },
  { value: "Logistics", label: "Logistics" },
  { value: "Facilities", label: "Facilities" },
  { value: "Security", label: "Security" },
  { value: "Project_Management", label: "Project Management" },
  {
    value: "Public_Relations_Communications",
    label: "Public Relations Communications",
  },
  { value: "Investor_Relations", label: "Investor Relations" },
  { value: "Compliance", label: "Compliance" },
];
