export const industries = [
  { value: "IT", label: "Information Technology" },
  { value: "Healthcare", label: "Healthcare" },
  { value: "Education", label: "Education" },
  { value: "Finance", label: "Finance" },
  { value: "Retail", label: "Retail" },
  { value: "Manufacturing", label: "Manufacturing" },
  { value: "Construction", label: "Construction" },
  { value: "Transportation", label: "Transportation" },
  { value: "Hospitality", label: "Hospitality" },
  { value: "Energy", label: "Energy" },
  { value: "Telecommunications", label: "Telecommunications" },
  { value: "Media & Entertainment", label: "Media & Entertainment" },
  { value: "Government", label: "Government" },
  { value: "Non-Profit", label: "Non-Profit" },
  { value: "Other", label: "Other" },
];
